# Generated by Django 5.2.4 on 2025-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_pendingsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tokens",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
