# Generated by Django 5.2.4 on 2025-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
