# Generated by Django 5.2.4 on 2025-08-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
