# Generated by Django 5.2.4 on 2025-08-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payement_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
