# Generated by Django 5.2.4 on 2025-08-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_subscription_payement_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="duration_type",
            field=models.CharField(default="month", max_length=20),
        ),
    ]
