# Generated by Django 5.2.4 on 2025-08-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_subscription_cancel_at_period_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokensPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens", models.IntegerField()),
                ("price_cents", models.IntegerField()),
            ],
        ),
    ]
