# Generated by Django 5.2.4 on 2025-08-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_tokensprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tokensprice",
            old_name="price_cents",
            new_name="price_in_cents",
        ),
        migrations.RemoveField(
            model_name="tokensprice",
            name="tokens",
        ),
        migrations.AddField(
            model_name="tokensprice",
            name="quantity_of_tokens",
            field=models.IntegerField(default=1),
        ),
    ]
