# Generated by Django 5.2.4 on 2025-08-29 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_price_cents_tokensprice_price_in_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokensprice",
            name="stripe_price_id",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
