# Generated by Django 5.2.4 on 2025-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_tokensprice_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokensprice",
            name="maximum_quantity_to_buy",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="tokensprice",
            name="minimum_quantity_to_buy",
            field=models.IntegerField(default=1),
        ),
    ]
