# Generated by Django 5.2.4 on 2025-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_tokensprice_maximum_quantity_to_buy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
